In [1]:
import pandas as pd
import numpy as np

In [2]:
from pandas import Series, DataFrame

In [3]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),
                  ......:columns=list('abcd'))

In [5]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),
                  ......:columns=list('abcde'))

In [6]:
df2.loc[1,'b'] = np.nan

In [7]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [8]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [9]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [10]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [11]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [12]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [13]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [14]:
arr = np.arange(12.).reshape((3,4))

In [15]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [16]:
arr[0]

array([0., 1., 2., 3.])

In [17]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [18]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                    ......:columns=list('bde'),
                    ......:index=['Los Santos','San Fierro','Las Venturas','Liberty City'])

In [19]:
series = frame.iloc[0]

In [20]:
frame

b     d     e
Los Santos    0.0   1.0   2.0
San Fierro    3.0   4.0   5.0
Las Venturas  6.0   7.0   8.0
Liberty City  9.0  10.0  11.0

In [21]:
series

b    0.0
d    1.0
e    2.0
Name: Los Santos, dtype: float64

In [22]:
frame - series

b    d    e
Los Santos    0.0  0.0  0.0
San Fierro    3.0  3.0  3.0
Las Venturas  6.0  6.0  6.0
Liberty City  9.0  9.0  9.0

In [23]:
series2 = pd.Series(range(3), index=['b','e','f'])

In [24]:
frame + series2

b   d     e   f
Los Santos    0.0 NaN   3.0 NaN
San Fierro    3.0 NaN   6.0 NaN
Las Venturas  6.0 NaN   9.0 NaN
Liberty City  9.0 NaN  12.0 NaN

In [25]:
series3 = frame['d']

In [26]:
frame

b     d     e
Los Santos    0.0   1.0   2.0
San Fierro    3.0   4.0   5.0
Las Venturas  6.0   7.0   8.0
Liberty City  9.0  10.0  11.0

In [27]:
series3

Los Santos       1.0
San Fierro       4.0
Las Venturas     7.0
Liberty City    10.0
Name: d, dtype: float64

In [28]:
frame.sub(series3, axis='index')

b    d    e
Los Santos   -1.0  0.0  1.0
San Fierro   -1.0  0.0  1.0
Las Venturas -1.0  0.0  1.0
Liberty City -1.0  0.0  1.0

In [29]:
frame = pd.DataFrame(np.random.randn(4,3), columns=list('bde'),
                    ......:index=['Toscana','Florença','Roma','Milão'])

In [30]:
frame

b         d         e
Toscana  -0.633501 -0.535258 -0.093173
Florença -0.603786 -0.485247  0.738705
Roma     -2.139592  0.865363  0.718815
Milão     0.688378 -1.287921  0.473782

In [31]:
np.abs(frame)

b         d         e
Toscana   0.633501  0.535258  0.093173
Florença  0.603786  0.485247  0.738705
Roma      2.139592  0.865363  0.718815
Milão     0.688378  1.287921  0.473782

In [32]:
f = lambda x: x.max() - x.min()

In [33]:
frame.apply(f)

b    2.827970
d    2.153284
e    0.831878
dtype: float64

In [34]:
format = lambda x: '%.2f' % x

In [35]:
frame.applymap(format)

/run/user/1000/app/org.jupyter.JupyterLab/ipykernel_226/304758519.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  frame.applymap(format)


b      d      e
Toscana   -0.63  -0.54  -0.09
Florença  -0.60  -0.49   0.74
Roma      -2.14   0.87   0.72
Milão      0.69  -1.29   0.47

In [36]:
frame['e'].map(format)

Toscana     -0.09
Florença     0.74
Roma         0.72
Milão        0.47
Name: e, dtype: object

In [37]:
obj = pd.Series(range(4), index=['d','a','b','c'])

In [38]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [40]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                    ......:index=['three','one'],
                    ......:columns=['d','a','b','c'])

In [41]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [42]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [43]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [44]:
obj = pd.Series([4,7,-3,2])

In [45]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [46]:
obj = pd.Series([4,np.nan,7,np.nan,-3,2])

In [47]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [48]:
frame = pd.DataFrame({'b': [4,7,-3,2], 'a':[0,1,0,1]})

In [49]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [50]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [51]:
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [52]:
obj = pd.Series([7,-5,7,4,2,0,4])

In [53]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [54]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [55]:
obj.rank(ascending=False,method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [56]:
frame = pd.DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],
                     ......:'c':[-2,5,8,-2.5]})

In [57]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [58]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [59]:
obj = pd.Series(range(5), index=['a','a','b','b','c'])

In [60]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [61]:
obj.index.is_unique

False

In [62]:
obj['a']

a    0
a    1
dtype: int64

In [63]:
obj['c']

4

In [64]:
df = pd.DataFrame(np.random.randn(4,3), index=['a','a','b','b'])

In [65]:
df

0         1         2
a  0.761395  0.979014  0.388080
a  0.798954 -0.221269 -0.290999
b -0.154993  1.003486  0.941048
b  0.744313  0.393152 -0.830591

In [66]:
df.loc['b']

0         1         2
b -0.154993  1.003486  0.941048
b  0.744313  0.393152 -0.830591

In [67]:
df = pd.DataFrame([[1.4, np.nan], [7.1,-4.5],
                  ......:[np.nan, np.nan], [0.75,-1.3]],
                  ......:index=['a','b','c','d'],
                  ......:columns=['one','two'])

In [68]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [69]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [70]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [71]:
df.mean(axis='columns',skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [72]:
df.idxmax()

one    b
two    d
dtype: object

In [73]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [74]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [75]:
obj = pd.Series(['a','a','b','c'] * 4)

In [76]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [78]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [79]:
uniques = obj.unique()

In [80]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [82]:
obj.value_counts()

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [83]:
pd.value_counts(obj.values, sort=False)

/run/user/1000/app/org.jupyter.JupyterLab/ipykernel_226/3084372382.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(obj.values, sort=False)


c    3
a    3
d    1
b    2
Name: count, dtype: int64

In [84]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [85]:
mask = obj.isin(['b','c'])

In [86]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [87]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [88]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [89]:
unique_vals = pd.Series(['c', 'b', 'a'])

In [90]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2])

In [91]:
data = pd.DataFrame({'Qu1':[1,3,4,3,4],
                    ......:'Qu2':[2,3,1,2,3],
                    ......:'Qu3':[1,5,2,4,4]})

In [92]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [93]:
result = data.apply(pd.value_counts).fillna(0)

/run/user/1000/app/org.jupyter.JupyterLab/ipykernel_226/2451317050.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  result = data.apply(pd.value_counts).fillna(0)


In [94]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0