In [1]:
import numpy as np

In [16]:
names = np.array(['Nick', 'Malik', 'Kletus', 'Mag', 'Andy', 'Caly', 'Mari'])

In [17]:
data = np.random.randn(7,4)

In [18]:
names

array(['Nick', 'Malik', 'Kletus', 'Mag', 'Andy', 'Caly', 'Mari'],
      dtype='<U6')

In [19]:
data

array([[ 0.41486769, -0.94508591,  0.39803807,  0.14243697],
       [-0.10041053, -0.17499309,  0.94684092,  0.6713132 ],
       [-0.58718567, -0.40659448, -0.33371095,  0.20573652],
       [ 0.48274299, -0.0617636 ,  0.19273515,  0.18600944],
       [-0.32281831, -0.75628462,  0.56957624, -0.9181326 ],
       [ 1.30612659,  0.24646903, -0.56939606, -0.4495123 ],
       [-2.38527575,  0.11651968, -1.51166642, -0.78805655]])

In [20]:
names == 'Nick'

array([ True, False, False, False, False, False, False])

In [21]:
data[names == 'Nick']

array([[ 0.41486769, -0.94508591,  0.39803807,  0.14243697]])

In [22]:
data[names == 'Nick',2:]

array([[0.39803807, 0.14243697]])

In [23]:
data[names == 'Nick', 3]

array([0.14243697])

In [24]:
names !='Nick'

array([False,  True,  True,  True,  True,  True,  True])

In [25]:
data[~(names == 'Nick')]

array([[-0.10041053, -0.17499309,  0.94684092,  0.6713132 ],
       [-0.58718567, -0.40659448, -0.33371095,  0.20573652],
       [ 0.48274299, -0.0617636 ,  0.19273515,  0.18600944],
       [-0.32281831, -0.75628462,  0.56957624, -0.9181326 ],
       [ 1.30612659,  0.24646903, -0.56939606, -0.4495123 ],
       [-2.38527575,  0.11651968, -1.51166642, -0.78805655]])

In [26]:
cond = names == 'Nick'

In [27]:
data[~cond]

array([[-0.10041053, -0.17499309,  0.94684092,  0.6713132 ],
       [-0.58718567, -0.40659448, -0.33371095,  0.20573652],
       [ 0.48274299, -0.0617636 ,  0.19273515,  0.18600944],
       [-0.32281831, -0.75628462,  0.56957624, -0.9181326 ],
       [ 1.30612659,  0.24646903, -0.56939606, -0.4495123 ],
       [-2.38527575,  0.11651968, -1.51166642, -0.78805655]])

In [28]:
mask = (names == 'Nick') | (names == 'Malik')

In [29]:
mask

array([ True,  True, False, False, False, False, False])

In [30]:
data[mask]

array([[ 0.41486769, -0.94508591,  0.39803807,  0.14243697],
       [-0.10041053, -0.17499309,  0.94684092,  0.6713132 ]])

In [31]:
data[data < 0] = 0

In [32]:
data

array([[0.41486769, 0.        , 0.39803807, 0.14243697],
       [0.        , 0.        , 0.94684092, 0.6713132 ],
       [0.        , 0.        , 0.        , 0.20573652],
       [0.48274299, 0.        , 0.19273515, 0.18600944],
       [0.        , 0.        , 0.56957624, 0.        ],
       [1.30612659, 0.24646903, 0.        , 0.        ],
       [0.        , 0.11651968, 0.        , 0.        ]])

In [33]:
data[names != 'Malik'] = 7

In [34]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.94684092, 0.6713132 ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ]])

In [35]:
arr = np.empty((8,4))

In [36]:
for i in range(8):
    arr[i] = i

In [37]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [38]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [39]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [40]:
arr = np.arange(32).reshape((8,4))

In [41]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [42]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [43]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [45]:
arr = np.arange(15).reshape((3,5))

In [46]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [48]:
arr = np.random.randn(6,3)

In [49]:
arr

array([[ 2.70389151e-01, -8.71720673e-01, -4.97009303e-01],
       [ 2.77067415e-01, -3.88735534e-01,  9.95977387e-01],
       [-1.77034793e-04, -3.37194850e-01, -9.58913136e-02],
       [ 1.48018083e+00,  2.82080388e+00,  6.40193051e-01],
       [ 8.99614808e-01,  7.21006123e-01,  4.36771123e-01],
       [ 3.69644515e-01,  3.87742124e-01,  5.05402048e-01]])

In [50]:
np.dot(arr.T,arr)

array([[3.28675584, 4.6239043 , 1.66893028],
       [4.6239043 , 9.65184092, 2.3951549 ],
       [1.66893028, 2.3951549 , 2.10423173]])

In [51]:
arr = np.arange(16).reshape((2,2,4))

In [52]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [53]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [54]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [55]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])