In [7]:
import numpy as np

In [8]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])

In [9]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [10]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [11]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [13]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [14]:
arr2 = np.array([[0.,4., 1.], [7.,2., 12.]])

In [15]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [16]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [17]:
arr = np.arange(10)

In [18]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr[5]

5

In [20]:
arr[5:8]

array([5, 6, 7])

In [21]:
arr[5:8] = 12

In [22]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [23]:
arr_slice = arr[5:8]

In [24]:
arr_slice

array([12, 12, 12])

In [25]:
arr_slice[1] = 12345

In [26]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [27]:
arr_slice[:] = 64

In [28]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [29]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])

In [30]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [34]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [35]:
arr2d[2]

array([7, 8, 9])

In [36]:
arr2d[0][2]

3

In [37]:
arr2d[0,2]

3

In [38]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [39]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [40]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
old_values = arr3d[0].copy()

In [42]:
arr3d[0] = 42

In [43]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [44]:
arr3d[0] = old_values

In [45]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
arr3d[1,0]

array([7, 8, 9])

In [48]:
x = arr3d[1]

In [49]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [50]:
x[0]

array([7, 8, 9])

In [51]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [52]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [53]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [56]:
arr2d[1,:2]

array([4, 5])

In [57]:
arr2d[:2,2]

array([3, 6])

In [58]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [59]:
arr2d[:2,1:] = 0

In [60]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])