In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
arr.dtype

dtype('int64')

In [4]:
float_arr = arr.astype(np.float64)

In [5]:
float_arr.dtype

dtype('float64')

In [7]:
arr = np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])

In [8]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [13]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [14]:
numeric_string = np.array(['1.25','-9.6','42'],dtype=np.string_)

In [15]:
numeric_string.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [16]:
int_array = np.arange(10)

In [17]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [18]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [19]:
empty_uint32 = np.empty(8, dtype='u4')

In [20]:
empty_uint32

array([1533576527,      21985,          0,          0,   86559184,
            21988,   86559104,      21988], dtype=uint32)